Controllers:
  controller-0:
    partition_a: 250
    partition_b: 250
    partition_d: 50
    memory_size: 16384
    system_cores: 4
  controller-1:
    partition_a: 250
    partition_b: 250
    partition_d: 50
    memory_size: 16384
    system_cores: 4
Computes:
  compute-0:
    partition_a: 250
    partition_b: 250
    memory_size: 10240
    system_cores: 3
  compute-1:
    partition_a: 250
    partition_b: 250
    memory_size: 10240
    system_cores: 3
general_system_configurations:
  os_system_memory: 1024
  disk_space_allocated_to_os: 20
  os_system_cores: 2
  default_mount_point: '/'
