apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-config
  namespace: kube-system
data:
  snmpd.conf: |
    agentAddress udp:161
    agentAddress udp6:161
    sysObjectID 1.3.6.1.4.1.731.3
    sysServices 72
    mibs +ALL
    master agentx
    agentXSocket tcp:705
    view all included .1 80
    sysDescr {{ system_description }}
    sysContact {{ system_contact }}
    sysName {{ system_name }}
    sysLocation {{ system_location }}